declare module "@adyen/adyen-web" 
declare module "@adyen/adyen-web/dist/types/components/ApplePay" 
declare module "@adyen/adyen-web/dist/types/components/GooglePay" 
declare module "@adyen/adyen-web/dist/types/core" 
declare module "@adyen/adyen-web/dist/types/core/core" 
declare module "@adyen/adyen-web/dist/types/components/Redirect/Redirect" 
declare module "@adyen/adyen-web/dist/types/core/types"
