name: Preview

on:
  push:
    tags:
      # Release tags v1.0.0, v1.0.1, v1.0.2, etc.
      - 'v[0-9]+.[0-9]+.[0-9]+'
      # Pre-release tags v1.0.0-alpha.0, v1.0.0-beta.0, etc.
      - 'v[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+'
      - latest
      - ddelizia-test
  workflow_dispatch:

jobs:
  publish:
    name: Preview Connector
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install
        env:
          CKO_CLIENT_ID: ${{ secrets.CKO_CLIENT_ID }}
          CKO_CLIENT_SECRET: ${{ secrets.CKO_CLIENT_SECRET }}
          CKO_CONNECTOR_KEY: ${{ secrets.CKO_CONNECTOR_KEY }}
        run: |
          echo Updating connector to tag $GITHUB_REF_NAME
          
          echo Authenticating with commercetools

          OAUTH_RESPONSE=$(curl --silent --show-error --location --request POST 'https://auth.europe-west1.gcp.commercetools.com/oauth/token?grant_type=client_credentials' -u $CKO_CLIENT_ID:$CKO_CLIENT_SECRET)
          
          ACCESS_TOKEN=$(echo $OAUTH_RESPONSE | jq -r '.access_token')
          echo Access token retrieved
          
          CONNECTOR_DETAILS=$(curl --silent --show-error --location "https://connect.europe-west1.gcp.commercetools.com/connectors/drafts/key=$CKO_CONNECTOR_KEY" \
              --header 'Content-Type: application/json' \
              --header "Authorization: Bearer $ACCESS_TOKEN")
          
          VERSION=$(echo $CONNECTOR_DETAILS | jq -r '.version')

          echo Updating version $VERSION
          
          curl --fail-with-body --silent --location POST "https://connect.europe-west1.gcp.commercetools.com/connectors/drafts/key=$CKO_CONNECTOR_KEY" \
              --header 'Content-Type: application/json' \
              --header "Authorization: Bearer $ACCESS_TOKEN" \
              --data-raw "{\"version\": $VERSION, \"actions\": [{\"action\": \"setRepository\",\"url\": \"git@github.com:commercetools/connect-payment-integration-adyen.git\",\"tag\": \"$GITHUB_REF_NAME\"},{\"action\": \"updatePreviewable\"}]}"

          # Validate when the `isPreviewable` is done
          while true; do
            # Execute the curl request and capture the response
            RESPONSE=$(curl --silent --show-error --location "https://connect.europe-west1.gcp.commercetools.com/connectors/drafts/key=$CKO_CONNECTOR_KEY" \
              --header 'Content-Type: application/json' \
              --header "Authorization: Bearer $ACCESS_TOKEN")
            
            STATUS=$(echo "$RESPONSE" | jq -r '.isPreviewable')
  
            # Check if the `isPreviewable` is still "pending"
            if [ "$STATUS" != "pending" ]; then
              # If it has changed, set it as an environment variable
              export PREVIEW_STATUS="$STATUS"
              break
            fi
            
            # Optional: add a delay to avoid spamming the server with requests
            sleep 5
          done

          echo "isPreviewable has changed to: $PREVIEW_STATUS"
          
          # Check if `PREVIEW_STATUS` is "true"
          if [ "$PREVIEW_STATUS" != "true" ]; then
            echo "Error: isPreviable is not 'true'. Exiting with failure."
            exit 1  # Exit with a non-zero status to indicate failure
          fi

          # npm install -g @commercetools/cli
          # commercetools auth login --client-credentials --client-id $CKO_CLIENT_ID --client-secret $CKO_CLIENT_SECRET --region europe-west1.gcp
          # commercetools connect connectorstaged update --key $CKO_CONNECTOR_KEY --repository-tag $GITHUB_REF_NAME
          # commercetools connect connectorstaged update --key $CKO_CONNECTOR_KEY
          